services:
  - type: web
    name: cinesplit-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinesplit-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cinesplit-redis
          property: connectionString
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MONGO_URI
        sync: false

  - type: redis
    name: cinesplit-redis
    plan: free

databases:
  - name: cinesplit-postgres
    databaseName: cinesplit
    user: cinesplit_user
    plan: free
